// EcoQuest AI Data Layer
// Stores all static data sets for the application

window.EcoQuestData = {
  // Badges structure
  badges: [
    {
      id: 'eco-beginner',
      name: 'Eco Beginner',
      desc: 'Calculate your carbon footprint for the first time.',
      icon: '🌱',
      color: 'from-emerald-400 to-teal-500',
      requirement: 'Complete the carbon footprint questionnaire.'
    },
    {
      id: 'green-explorer',
      name: 'Green Explorer',
      desc: 'Complete 3 daily eco-missions.',
      icon: '🧭',
      color: 'from-teal-400 to-cyan-500',
      requirement: 'Complete 3 daily missions.'
    },
    {
      id: 'planet-protector',
      name: 'Planet Protector',
      desc: 'Reach a Carbon Score of 80 or above.',
      icon: '🛡️',
      color: 'from-green-400 to-emerald-600',
      requirement: 'Achieve a Carbon Score >= 80.'
    },
    {
      id: 'climate-champion',
      name: 'Climate Champion',
      desc: 'Complete a multi-day sustainability challenge.',
      icon: '🏆',
      color: 'from-yellow-400 to-amber-500',
      requirement: 'Join and complete any Carbon Reduction Challenge.'
    },
    {
      id: 'carbon-ninja',
      name: 'Carbon Ninja',
      desc: 'Reach Rank 1 on the Weekly Leaderboard.',
      icon: '🥷',
      color: 'from-purple-500 to-indigo-600',
      requirement: 'Reach the top spot on the community leaderboard.'
    }
  ],

  // Quiz Questions structure
  quizQuestions: [
    {
      id: 1,
      question: "Which of the following transport methods has the LOWEST carbon footprint per passenger-kilometer?",
      options: [
        "Gasoline-powered Car",
        "Electric Train (Rail)",
        "Commercial Airplane",
        "Hybrid SUV"
      ],
      correctIndex: 1,
      explanation: "Electric trains are highly efficient and transport large numbers of people simultaneously, resulting in the lowest emissions per passenger-kilometer compared to cars and planes."
    },
    {
      id: 2,
      question: "What is 'phantom energy' (or standby power)?",
      options: [
        "Energy used by solar panels at night",
        "Electricity consumed by appliances when they are switched off but still plugged in",
        "Static electricity generated by synthetic fabrics",
        "Energy lost in transmission lines"
      ],
      correctIndex: 1,
      explanation: "Phantom energy refers to the power drawn by chargers, TVs, and computers when plugged in but not in active use. It can account for up to 10% of a home's electricity bill."
    },
    {
      id: 3,
      question: "Which diet generally produces the lowest greenhouse gas emissions?",
      options: [
        "Lacto-ovo vegetarian diet",
        "Fully plant-based (vegan) diet",
        "Mediterranean diet (rich in fish and oil)",
        "High-protein meat diet"
      ],
      correctIndex: 1,
      explanation: "A fully plant-based (vegan) diet avoids livestock farming, which is a major source of methane and deforestation emissions, resulting in the lowest carbon footprint."
    },
    {
      id: 4,
      question: "What is the primary greenhouse gas emitted by decomposing organic waste in landfills?",
      options: [
        "Carbon Dioxide",
        "Methane",
        "Nitrous Oxide",
        "Chlorofluorocarbons"
      ],
      correctIndex: 1,
      explanation: "Decomposing organic waste in anaerobic (oxygen-poor) landfills creates methane, a greenhouse gas that is over 25 times more potent than carbon dioxide at trapping heat."
    },
    {
      id: 5,
      question: "How does buying fast fashion impact the climate?",
      options: [
        "It uses minimal water and causes low emissions",
        "It generates massive emissions due to synthetic material production and rapid disposal landfills",
        "It helps local ecosystems capture carbon",
        "It is neutral because clothes are biodegradable"
      ],
      correctIndex: 1,
      explanation: "Fast fashion relies on polyester (made from petroleum) and quick-turnaround production. It causes huge emissions, high water consumption, and leads to millions of tons of textile waste in landfills yearly."
    },
    {
      id: 6,
      question: "Which bulb type consumes the least energy and has the longest lifespan?",
      options: [
        "Incandescent Bulb",
        "Halogen Bulb",
        "Compact Fluorescent Lamp (CFL)",
        "Light Emitting Diode (LED)"
      ],
      correctIndex: 3,
      explanation: "LEDs use up to 80% less energy than incandescents and can last 25 times longer, saving substantial money and emissions over time."
    },
    {
      id: 7,
      question: "What does the term 'Carbon Offsetting' mean?",
      options: [
        "Avoiding emissions by not using appliances",
        "Funding projects that reduce or sequester carbon to compensate for emissions made elsewhere",
        "Increasing emissions to speed up industrial manufacturing",
        "Selling carbon rights on the open stock exchange"
      ],
      correctIndex: 1,
      explanation: "Carbon offsetting involves paying for external projects, like planting trees or building renewable wind farms, to capture or avoid greenhouse gases, balancing out your own emissions."
    }
  ],

  // Knowledge Center structure
  knowledgeCenter: [
    {
      title: "Understanding Carbon Footprint",
      category: "Basics",
      summary: "What is a carbon footprint, and why does measuring it help us build a more sustainable future?",
      content: "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) generated by our actions. Globally, the average carbon footprint is close to 4 tons per person annually, but in developed countries, it is often 10-15 tons. Reducing our footprint to under 2 tons per person is critical to keeping global temperature rises below 1.5°C."
    },
    {
      title: "The Impact of Phantom Loads",
      category: "Energy",
      summary: "How appliances left plugged in secretly drain energy and raise your utility bills.",
      content: "Even when turned off, many appliances (microwave clocks, gaming consoles, TV standbys, chargers) remain in standby mode, consuming power. Unplugging devices when not in use or using smart power strips can cut annual household emissions by 200kg of CO2 and save money on electricity bills."
    },
    {
      title: "Dietary Changes and Carbon Savings",
      category: "Food",
      summary: "Comparing the carbon footprint of meat production to plant-based alternatives.",
      content: "Beef production generates nearly 60 times more greenhouse gases than wheat per kilogram. Livestock requires massive pasture space, which causes deforestation, and cows release methane during digestion. Replacing just one meat meal a day with a plant-based alternative can reduce your yearly footprint by 400kg of CO2."
    },
    {
      title: "Circular Economy vs. Linear Economy",
      category: "Shopping",
      summary: "Rethinking waste through reduce, reuse, recycle, and repair.",
      content: "In a linear economy, we make, use, and dispose of goods. In a circular economy, materials are designed to be restored, repurposed, and recycled, eliminating waste. Choosing second-hand purchases, repairing electronics, and supporting brands that use recycled plastics helps prevent the extraction of virgin raw materials and reduces industrial production emissions."
    }
  ],

  // Default Daily Missions
  defaultMissions: [
    {
      id: 'm-1',
      title: 'Meat-Free Day',
      desc: 'Eat vegetarian or plant-based meals today.',
      xp: 40,
      difficulty: 'Medium',
      impact: 15, // kg CO2 saved
      category: 'Food'
    },
    {
      id: 'm-2',
      title: 'Power-Down Hour',
      desc: 'Turn off all non-essential screens and devices for 1 hour.',
      xp: 20,
      difficulty: 'Easy',
      impact: 5,
      category: 'Energy'
    },
    {
      id: 'm-3',
      title: 'Eco Transit',
      desc: 'Walk, cycle, or take public transport for all your trips today.',
      xp: 50,
      difficulty: 'Hard',
      impact: 20,
      category: 'Transport'
    },
    {
      id: 'm-4',
      title: 'Reusable Comrade',
      desc: 'Use a reusable bottle, coffee cup, and shopping bag today.',
      xp: 15,
      difficulty: 'Easy',
      impact: 4,
      category: 'Shopping'
    },
    {
      id: 'm-5',
      title: 'Standby Slayer',
      desc: 'Unplug 5 unused electronics or chargers from the wall sockets.',
      xp: 25,
      difficulty: 'Easy',
      impact: 8,
      category: 'Energy'
    }
  ],

  // Carbon Reduction Challenges
  challenges: [
    {
      id: 'c-1',
      title: '7-Day Zero Waste Challenge',
      desc: 'Commit to avoiding single-use plastics, composting food scraps, and purchasing items with minimal packaging for a full week.',
      duration: '7 Days',
      xpReward: 250,
      co2Reward: 45, // kg CO2 projected
      progressTotal: 7,
      enrolled: false,
      progressCurrent: 0,
      tips: [
        "Carry cloth bags everywhere.",
        "Refuse plastic straws and plastic cutlery.",
        "Compost organic leftovers.",
        "Buy grains and nuts in bulk containers."
      ]
    },
    {
      id: 'c-2',
      title: '15-Day Active Commute',
      desc: 'Swap all car trips under 3km with walking, running, cycling, or scootering to promote clean transit.',
      duration: '15 Days',
      xpReward: 500,
      co2Reward: 90,
      progressTotal: 15,
      enrolled: false,
      progressCurrent: 0,
      tips: [
        "Map out safe bike paths in your city.",
        "Leave 15 minutes earlier to enjoy a relaxing walk.",
        "Check weather forecasts ahead of time.",
        "Ensure your bicycle tires are properly inflated."
      ]
    },
    {
      id: 'c-3',
      title: '30-Day Energy Diet',
      desc: 'Reduce AC usage by 1 hour daily, switch off standby power, and wash clothes in cold water for a month.',
      duration: '30 Days',
      xpReward: 1000,
      co2Reward: 180,
      progressTotal: 30,
      enrolled: false,
      progressCurrent: 0,
      tips: [
        "Set AC thermostat to 24°C (75°F) or higher.",
        "Use natural ventilation during cooler evenings.",
        "Hang-dry clothes instead of using a heated dryer.",
        "Unplug electronic appliances before sleeping."
      ]
    }
  ],

  // Mock Leaders
  mockLeaderboard: [
    { name: "Sophia Green", xp: 1450, missions: 28, isUser: false, avatar: "🟢" },
    { name: "Kai Solar", xp: 1220, missions: 22, isUser: false, avatar: "☀️" },
    { name: "Luna Leaf", xp: 980, missions: 18, isUser: false, avatar: "🍃" },
    { name: "Leo Eco", xp: 750, missions: 14, isUser: false, avatar: "🦊" },
    { name: "Emma Wind", xp: 580, missions: 9, isUser: false, avatar: "💨" },
    { name: "User (You)", xp: 0, missions: 0, isUser: true, avatar: "🛡️" }
  ]
};
